apiVersion: v1
kind: Service
metadata:
  name: <group-name>-backend-service
  namespace: <group-name>-app
spec:
  type: ClusterIP
  selector:
    app: <group-name>-backend
  ports:
    - port: 8080
      targetPort: 8080


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: <group-name>-backend-deployment
  namespace: <group-name>-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <group-name>-backend
  template:
    metadata:
      labels:
        app: <group-name>-backend
    spec:
      containers:
        - name: <group-name>-backend
          image: <dockerhub-username>/<backend-image-name>:<tag>
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"

            # ========= เลือกใช้ อันที่ Porject เราใช้ =========

            # PostgreSQL (Service name = muict, namespace = db-postgres)
            # - name: SPRING_DATASOURCE_URL
            #   value: "jdbc:postgresql://muict.db-postgres.svc.cluster.local:5432/<groupname>_db"

            # MySQL (Service name = muict-mysql, namespace = db-mysql)
            # - name: SPRING_DATASOURCE_URL
            #   value: "jdbc:mysql://muict-mysql.db-mysql.svc.cluster.local:3306/<groupname>_db"

            - name: SPRING_DATASOURCE_USERNAME
              value: "<groupname>_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "<password>"



