apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <group-name>-fe-ingress
  namespace: <group-name>-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - muict.app
      secretName: muict-app-tls
  rules:
    - host: muict.app
      http:
        paths:
          - path: /<group-name>-frontend
            pathType: Prefix
            backend:
              service:
                name: <group-name>-frontend-service
                port:
                  number: 80
