apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papapig99-be-ingress
  namespace: papapig99-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - muict.app
      secretName: muict-app-tls
  rules:
    - host: muict.app
      http:
        paths:
          - path: /papapig99-backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: papapig99-backend-service
                port:
                  number: 8080
