apiVersion: v1
kind: Service
metadata:
  name: papapig99-frontend-service
  namespace: papapig99-app
spec:
  selector:
    app: papapig99-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papapig99-frontend-deployment
  namespace: papapig99-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papapig99-frontend
  template:
    metadata:
      labels:
        app: papapig99-frontend
    spec:
      containers:
        - name: papapig99-frontend
          image: thitip/event-frontend:8c1a674e7b2a45c145455f2c9990aa3a40fa8edd
          ports:
            - containerPort: 80
          env:

            # ------------------------------------------------------
            # Option: 1 — ถ้า frontend ใช้ env API
            # ให้ uncomment ตัวนี้ แล้วแก้เป็น path ของกลุ่มตามนี้
            # ------------------------------------------------------
            # - name: NEXT_PUBLIC_API_URL
            #   value: "https://muict.app/<group-name>-backend"

            # - name: VITE_API_URL
            #   value: "https://muict.app/<group-name>-backend"

            # ------------------------------------------------------
            # Option: 2 — ถ้า frontend hardcode localhost
            # ต้องไปแก้ใน code เองเป็น:
            #   https://muict.app/<group-name>-backend
            # ไม่ต้องตั้ง env ที่นี่
            # แล้วก็ปล่อย comment ไว้แบบนี้ได้เลย 
            # ------------------------------------------------------


