apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papapig99-images-fix
  namespace: papapig99-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - muict.app
      secretName: muict-app-tls
  rules:
    - host: muict.app
      http:
        paths:
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: papapig99-backend-service
                port:
                  number: 8080