apiVersion: v1
kind: Service
metadata:
  name: chiphaifamily-frontend-service
  namespace: chiphaifamily-app
spec:
  selector:
    app: chiphaifamily-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chiphaifamily-frontend-deployment
  namespace: chiphaifamily-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chiphaifamily-frontend
  template:
    metadata:
      labels:
        app: chiphaifamily-frontend
    spec:
      containers:
        - name: chiphaifamily-frontend
          image: kbtr/apartment-frontend:0dc861474c9720c3a20e23eb6b4be9d73dd27158
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: "chiphaifamily-backend-service"
            # ------------------------------------------------------
            # Option: 1 — ถ้า frontend ใช้ env API
            # ให้ uncomment ตัวนี้ แล้วแก้เป็น path ของกลุ่มตามนี้
            # ------------------------------------------------------
            # - name: NEXT_PUBLIC_API_URL
            #   value: "https://muict.app/<group-name>-backend"

            - name: VITE_API_URL
              value: "https://muict.app/chiphaifamily-backend"

            # ------------------------------------------------------
            # Option: 2 — ถ้า frontend hardcode localhost
            # ต้องไปแก้ใน code เองเป็น:
            #   https://muict.app/<group-name>-backend
            # ไม่ต้องตั้ง env ที่นี่
            # แล้วก็ปล่อย comment ไว้แบบนี้ได้เลย 
            # ------------------------------------------------------



