apiVersion: v1
kind: Service
metadata:
  name: prodev-frontend-service
  namespace: prodev-app
spec:
  selector:
    app: prodev-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodev-frontend-deployment
  namespace: prodev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodev-frontend
  template:
    metadata:
      labels:
        app: prodev-frontend
    spec:
      containers:
        - name: prodev-frontend
          image: armmer/prodev-frontend:latest
          ports:
            - containerPort: 80

          # ------------------------------------------------------
          # Option: 1 — ถ้า frontend ใช้ env API
          # ให้ uncomment ตัวนี้ แล้วแก้เป็น path ของกลุ่มตามนี้
          # ------------------------------------------------------
          # - name: NEXT_PUBLIC_API_URL
          #   value: "https://muict.app/<group-name>-backend"

          # - name: VITE_API_URL
          #   value: "https://muict.app/<group-name>-backend"

          # ------------------------------------------------------
          # Option: 2 — ถ้า frontend hardcode localhost
          # ต้องไปแก้ใน code เองเป็น:
          #   https://muict.app/<group-name>-backend
          # ไม่ต้องตั้ง env ที่นี่
          # แล้วก็ปล่อย comment ไว้แบบนี้ได้เลย
          # ------------------------------------------------------