apiVersion: v1
kind: Service
metadata:
  name: organicnow-frontend-service
  namespace: organicnow-app
spec:
  selector:
    app: organicnow-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: organicnow-frontend-deployment
  namespace: organicnow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organicnow-frontend
  template:
    metadata:
      labels:
        app: organicnow-frontend
    spec:
      containers:
        - name: organicnow-frontend
          image: <dockerhub-username>/<frontend-image-name>:<tag>
          ports:
            - containerPort: 80
          env:

            # ------------------------------------------------------
            # Option: 1 — ถ้า frontend ใช้ env API
            # ให้ uncomment ตัวนี้ แล้วแก้เป็น path ของกลุ่มตามนี้
            # ------------------------------------------------------
            - name: NEXT_PUBLIC_API_URL
              value: "https://muict.app/organicnow-backend"

            - name: VITE_API_URL
              value: "https://muict.app/organicnow-backend"

            # ------------------------------------------------------
            # Option: 2 — ถ้า frontend hardcode localhost
            # ต้องไปแก้ใน code เองเป็น:
            #   https://muict.app/<group-name>-backend
            # ไม่ต้องตั้ง env ที่นี่
            # แล้วก็ปล่อย comment ไว้แบบนี้ได้เลย 
            # ------------------------------------------------------



