apiVersion: v1
kind: Service
metadata:
  name: 5tuay10bath-backend-service
  namespace: 5tuay10bath-app
spec:
  type: ClusterIP
  selector:
    app: 5tuay10bath-backend
  ports:
    - port: 8080
      targetPort: 8080


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: 5tuay10bath-backend-deployment
  namespace: 5tuay10bath-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 5tuay10bath-backend
  template:
    metadata:
      labels:
        app: 5tuay10bath-backend
    spec:
      containers:
        - name: 5tuay10bath-backend
          image: iamyasuomain/deawkoikid_backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"

            # ========= เลือกใช้ อันที่ Porject เราใช้ =========

            # PostgreSQL (Service name = muict, namespace = db-postgres)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://muict.db-postgres.svc.cluster.local:5432/5tuay10bath_db"

            # MySQL (Service name = muict-mysql, namespace = db-mysql)
            # - name: SPRING_DATASOURCE_URL
            #   value: "jdbc:mysql://muict-mysql.db-mysql.svc.cluster.local:3306/<groupname>_db"

            - name: SPRING_DATASOURCE_USERNAME
              value: "5tuay10bath_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "<password>"



