apiVersion: v1
kind: Service
metadata:
  name: fivetuay10bath-backend-service
  namespace: fivetuay10bath-app
spec:
  type: ClusterIP
  selector:
    app: fivetuay10bath-backend
  ports:
    - port: 8080
      targetPort: 8080


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: fivetuay10bath-backend-deployment
  namespace: fivetuay10bath-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fivetuay10bath-backend
  template:
    metadata:
      labels:
        app: fivetuay10bath-backend
    spec:
      containers:
        - name: fivetuay10bath-backend
          image: iamyasuomain/deawkoikid_backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"

            # ========= เลือกใช้ อันที่ Porject เราใช้ =========

            # PostgreSQL (Service name = muict, namespace = db-postgres)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://muict.db-postgres.svc.cluster.local:5432/fivetuay10bath_db"

            # MySQL (Service name = muict-mysql, namespace = db-mysql)
            # - name: SPRING_DATASOURCE_URL
            #   value: "jdbc:mysql://muict-mysql.db-mysql.svc.cluster.local:3306/<groupname>_db"

            - name: SPRING_DATASOURCE_USERNAME
              value: "fivetuay10bath_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "fivetuay10bath_pass"

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-aws-secrets      
                  key: AWS_ACCESS_KEY_ID    

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-secrets
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: my-aws-secrets
                  key: AWS_REGION

            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: my-aws-secrets
                  key: AWS_BUCKET_NAME



