apiVersion: v1
kind: Service
metadata:
  name: 5tuay10bath-frontend-service
  namespace: 5tuay10bath-app
spec:
  selector:
    app: 5tuay10bath-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP

---

piVersion: apps/v1
kind: Deployment
metadata:
  name: 5tuay10bath-frontend-deployment
  namespace: 5tuay10bath-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 5tuay10bath-frontend
  template:
    metadata:
      labels:
        app: 5tuay10bath-frontend
    spec:
      containers:
        - name: 5tuay10bath-frontend
          image: iamyasuomain/deawkoikid_frontend:latest
          ports:
            - containerPort: 3000
          env:

            # ------------------------------------------------------
            # Option: 1 — ถ้า frontend ใช้ env API
            # ให้ uncomment ตัวนี้ แล้วแก้เป็น path ของกลุ่มตามนี้
            # ------------------------------------------------------
            # - name: NEXT_PUBLIC_API_URL
            #   value: "https://muict.app/5tuay10bath-backend"

            - name: VITE_API_URL
              value: "https://muict.app/5tuay10bath-backend"

            # ------------------------------------------------------
            # Option: 2 — ถ้า frontend hardcode localhost
            # ต้องไปแก้ใน code เองเป็น:
            #   https://muict.app/5tuay10bath-backend
            # ไม่ต้องตั้ง env ที่นี่
            # แล้วก็ปล่อย comment ไว้แบบนี้ได้เลย 
            # ------------------------------------------------------



