apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmm-fe-deployment
  namespace: salad-pirate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmm-fe
  template:
    metadata:
      labels:
        app: pmm-fe
    spec:
      containers:
        - name: pmm-fe
          image: chitipatpangma/pmm_fe:2f4aded
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pmm-fe-service
  namespace: salad-pirate-app
spec:
  selector:
    app: pmm-fe
  ports:
    - port: 80
      targetPort: 3000
